# Normal

In [9]:
from PIL import Image
import numpy as np

im = np.array(Image.open('./trimmed.jpg'))

print(type(im))

<class 'numpy.ndarray'>


In [10]:
im

array([[[121, 191, 225],
        [122, 192, 226],
        [122, 192, 226],
        ...,
        [122, 192, 228],
        [123, 193, 229],
        [126, 196, 232]],

       [[121, 191, 225],
        [122, 192, 226],
        [122, 192, 226],
        ...,
        [122, 192, 228],
        [123, 193, 229],
        [126, 196, 232]],

       [[121, 191, 225],
        [122, 192, 226],
        [122, 192, 226],
        ...,
        [122, 192, 228],
        [123, 193, 229],
        [126, 196, 232]],

       ...,

       [[121, 191, 225],
        [122, 192, 226],
        [122, 192, 226],
        ...,
        [122, 192, 228],
        [123, 193, 229],
        [126, 196, 232]],

       [[121, 191, 225],
        [122, 192, 226],
        [122, 192, 226],
        ...,
        [122, 192, 228],
        [123, 193, 229],
        [126, 196, 232]],

       [[121, 191, 225],
        [122, 192, 226],
        [122, 192, 226],
        ...,
        [122, 192, 228],
        [123, 193, 229],
        [126, 196, 232]]

In [11]:
print(im.shape)

(420, 420, 3)


# Gray

In [12]:
im_gray = np.array(Image.open('./trimmed.jpg').convert('L'))

In [13]:
im_gray

array([[174, 175, 175, ..., 175, 176, 179],
       [174, 175, 175, ..., 175, 176, 179],
       [174, 175, 175, ..., 175, 176, 179],
       ...,
       [174, 175, 175, ..., 175, 176, 179],
       [174, 175, 175, ..., 175, 176, 179],
       [174, 175, 175, ..., 175, 176, 179]], dtype=uint8)

In [14]:
print(im_gray.shape)

(420, 420)


In [15]:
pil_img = Image.fromarray(im_gray)
pil_img.save('./output/gray.jpg')

# Resize

In [17]:
img = Image.open('./trimmed.jpg')
im_resize = img.resize((48, 48))

In [19]:
im_resize.save('./output/resize.jpg')

# まとめ

### 正方形の画像をグレースケール化&resize

In [37]:
from PIL import Image
import numpy as np

In [38]:
gray = Image.open('./trimmed.jpg').convert('L')
im_resize = gray.resize((48, 48))

In [39]:
im_resize.save('./output/test.jpg')

### import

In [40]:
im = np.array(Image.open('./output/test.jpg'))

In [41]:
im

array([[177, 168, 184, ..., 183, 175, 171],
       [178, 173, 183, ..., 176, 169, 179],
       [175, 178, 178, ..., 174, 171, 176],
       ...,
       [175, 175, 175, ..., 175, 175, 175],
       [175, 175, 175, ..., 175, 175, 175],
       [175, 175, 175, ..., 175, 175, 175]], dtype=uint8)

In [42]:
print(im.shape)

(48, 48)


# Test

In [45]:
im = im.reshape(1,48,48,1)

In [46]:
print(im.shape)

(1, 48, 48, 1)
